[web]
ubuntu-worker ansible_host=YOUR_WEB_SERVER_IP ansible_user=ubuntu

[app]
redhat-worker ansible_host=YOUR_WEB_SERVER_IP ansible_user=ec2-user

[db]
amazon-worker ansible_host=YOUR_WEB_SERVER_IP ansible_user=ec2-user

[all:vars]
ansible_ssh_private_key_file=~/terra-ansible-key